name: Deploy monorepo project

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  deploy-project:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        apps:
          [
            { name: "web", secret: "PROJECT_WEB_ID" },
            { name: "dashboard", secret: "PROJECT_DASHBOARD_ID" },
          ]

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets[matrix.apps.secret] }}

    steps:
      - name: code checkout
        uses: actions/checkout@v7

      - name: setup node and pnpm cache
        uses: pnpm/setup@v1
        with:
          runtime: node@22
          cache: true

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      - name: Approve scripts
        run: pnpm approve-builds --all

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel ${{matrix.apps.name}}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
